#服务启动端口
server:
  #配置端口号
  port: 20400
  servlet:
    #配置项目的路径
      context-path: /wechatlogin
  tomcat:
    #配置tomcat编码
    uri-encoding: utf-8
    #配置tomcat最大连接数
    max-connections: 300
    #配置tomcat最小连接数
    accept-count: 30

#Spring
spring:
  profiles:
    active: wechatminiprogram

  ## MULTIPART (MultipartProperties)
  # Enable multipart uploads
  servlet:
    multipart:
      enabled: true
      # Threshold after which files are written to disk.
      file-size-threshold: 2KB
      # Max file size.
      max-file-size: 200MB
      # Max Request Size
      max-request-size: 215MB



